### ISSUE TITLE
Explicit requirement for inclusion of agency OGC in policy development

### ISSUE THREAD

**Issue by egyptiankarim** [cisagov/cyber.dhs.gov#103]
> #### Develop and Publish a Vulnerability Disclosure Policy
> [...]
> 3. Publish a vulnerability disclosure policy as a web page in plain
>     text or HTML.
> [...]
> a)  The policy **must** include:
> [...]
> iv. *A commitment to not recommend or pursue legal action*
> against anyone for security research activities that the
> agency concludes represents a good faith effort to follow
> the policy, and *deem that activity authorized*.

It's worth considering that this BOD will probably initially land amongst OCIO (i.e., the "techy" crowd), but the required deliverables need to be worked alongside the "lawyerly" folks at any given agency. Specifically, the section quoted above could use a subordinate clause that states OGC has reviewed and concurred with any assertions made regarding pursuit of legal action.

I can work a pull request with some draft language.

**Comment by h-m-f-t** [comment]
Do feel free to file PRs, please.

**Comment by egyptiankarim** [comment]
@h-m-f-t actively working some drafted up language in a fork, here: https://github.com/egyptiankarim/cyber.dhs.gov/commit/17aebfd0dbfd32d86a26356da960b8c92f8b07c2

I'm passing the edits through some of the legal folks at my agency before I file the pull request :)

**Comment by konklone** [comment]
> Specifically, the section quoted above could use a subordinate clause that states OGC has reviewed and concurred with any assertions made regarding pursuit of legal action.

Personal opinion - I can most easily see this as constructive in the form of an explicit suggestion to agencies (rather than a statement to researchers) that they consult their OGC while finalizing their language.

**Comment by egyptiankarim** [comment]
> an explicit suggestion to agencies (rather than a statement to researchers) that they consult their OGC while finalizing their language.

That’s exactly how I intended it, and I believe how the language in the PR would read based on where it’s placed. My intention was for this language to be addressing agencies, not researchers.
