### ISSUE TITLE
Recommend Availability of Encryption  (i.e.: PGP)  to secure report submission

### ISSUE THREAD

**Issue by chudel** [cisagov/cyber.dhs.gov#113]
While a web-based form will naturally use a secure communication protocol (HTTP over TLS, for example), email is often not secure from end-to-end.

Where the severity of a potential vulnerability warrants it, or at a security researcher's discretion, a secure email communication channel should be made available.  This may be as simple as adding a "PGP Key" (a public key component used in public/private key cryptograph) to the security.txt file.

To be clear, I mean that secure end-to-end email reporting and discussion should be available to researchers and agencies, not that it should be mandatory.

**Comment by zmanion** [comment]
While I'm a die-hard PGP fan, and we (CERT/CC) use PGP operationally, I would not recommend it as a requirement due to difficulty of use. No concerns if an agency optionally wants to support PGP.
