### ISSUE TITLE
VE-2020-1472.ps1 assumes insecure WinRM protocol, Fails when using TLS

### ISSUE THREAD

**Issue by ElSrJuez** [cisagov/cyber.dhs.gov#166]
The script fails when remote management is enabled only via Secure WinRM (SSL/TLS TCP 5986).
Examples:
    $HotFixInfo = invoke-command -computername $dc -UseSSL -scriptblock {
        Get-WmiObject Win32_quickfixengineering | Select-Object *
    }

Invoke-Command -ComputerName $DC -UseSSL -ScriptBlock { $Session = New-Object -ComObject Microsoft.Update.Session ; $UpdateSearch = $Session.CreateUpdateSearcher() ; $UpdateSearch.Search("IsInstalled=1").Updates | select Title }

**Comment by h-m-f-t** [comment]
Thanks @ElSrJuez 👋
