### ISSUE TITLE
BOD 18-01 references M-15-13, but does not include a duration.

### ISSUE THREAD

**Issue by ArchLayperson** [cisagov/cyber.dhs.gov#194]
M-15-13 contains a footnote that specifies HSTS's max-age should be one year or greater, but this is not replicated in the text, nor in the compliance guide of 18-01. As 18-01 is already published, there may not be any method to make this information more prominent, however, the fact that this information is not contained in the BOD (nor the Memo's main text) can lead to confusion.

**Comment by h-m-f-t** [comment]
[18-01.md](https://github.com/cisagov/cyber.dhs.gov/blob/master/pages/18-01.md) has 4 citations to various https://https.cio.gov/guide/ sections, including https://https.cio.gov/guide/#options-for-hsts-compliance which does have a sample HSTS string including the max-age.

Do you have any specific suggestions for text revisions? We can't change the directive or memo's text, but we'd welcome explaining things better in our guidance.

**Comment by ArchLayperson** [comment]
The only suggestions I can offer at this moment is adding it to the FAQ, and possibly adding something like `with max-age of one year or greater` to the compliance guide around line 334.

I tried writing text a few times for it, but I was unable to match the existing writing style in a way that looks reasonable.

**Comment by h-m-f-t** [comment]
Thanks, @ArchLayperson. Closing for now.
