### ISSUE TITLE
RSS Feeds for Site Updates

### ISSUE THREAD

**Issue by ohsh6o** [cisagov/cyber.dhs.gov#274]
As security engineer working in the public sector, in order to streamline and automate notification around important updates in guidance from DHS and CISA, I would like the RSS feed to be enabled so I can integrate it into tools that commonly support RSS for this purpose. This is a simple addition of a PR with a common plugin, [`jekyll-feed`](https://github.com/jekyll/jekyll-feed), used in many repositories by [federal government developers using the same static site generator](https://github.com/search?l=YAML&q=org%3A18F+jekyll-feed&type=Code).

NOTE: I believe that an increasing number of contractors and federal employees access and rely on Slack for day-to-day operational needs. In a commercial Slack space, I already do this with [NCAS alerts](https://us-cert.cisa.gov/ncas/all.xml), and it allows me to link into relevant channels and group reactions and operations follow-up by engineers around a particular notice from CISA. I cannot do this for BODs and EDs from this site however.

<img width="1086" alt="Screen Shot 2021-07-13 at 1 17 03 PM" src="https://user-images.githubusercontent.com/61464190/125496866-45f86af4-cf77-462a-ae76-55323ed70011.png">

**Comment by h-m-f-t** [comment]
(This should not have been closed; re-opening.)

Thanks for the suggestion, @ohsh6o.  We think this is a good idea and can plan to implement. It is somewhat likely that this site will be migrated into cisa.gov directly, though.

**Comment by h-m-f-t** [comment]
@ohsh60, this site is being retired in favor of cisa.gov/directives. (Sorry, it also lacks an RSS feed.)

**Comment by aj-stein-nist** [comment]
@h-m-f-t, this is new ohsh6o (courtesy of my new employer, NIST). Where I can send public feedback to DHS leadership explain why websites like this and/or RSS are so important and why GovDelivery is not sufficient for my use cases?

Thanks!

**Comment by h-m-f-t** [comment]
@aj-stein-nist :wave: Feel free to email me at cameron.dixon@cisa.dhs.gov and I'll share it up.
