### ISSUE TITLE
Add an FAQ regarding the pct flag

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/cyber.dhs.gov#29]
@seanthegeek makes an excellent point in the [trustymail repo](https://github.com/dhs-ncats/trustymail/pull/44#discussion_r158762921) about how an agency could sidestep the intent of the BOD: if a `pct` flag isn't used, the implicit value is 100. But in October, an agency could have `p=reject` but have that applied to less than 100 percent of mail from their domain. That's bad, and they should feel bad, so we should add some guidance.

**Comment by seanthegeek** [comment]
> That's bad, and they should feel bad

😆 👍

**Comment by boberlas** [comment]
PCT=100 is critical for a p=reject policy; is it required while implementing a p=none policy. The concern is relating to limits for destination rua email boxes.

**Comment by h-m-f-t** [comment]
Resolved back at #41 and #56.
