### ISSUE TITLE
Trustworthy Email Report

### ISSUE THREAD

**Issue by boberlas** [cisagov/cyber.dhs.gov#30]
The Trustworthy Email Report is tracking full compliance based on a p=reject policy which is technically not required until October 2018; recommend an interim measure of compliance to reflect compliance with p=none and Starttls that is separate and distinct from a full p=reject policy stance.

**Comment by h-m-f-t** [comment]
> Trustworthy Email Report is tracking full compliance based on a p=reject policy which is technically not required until October 2018

You are correct, and I want to acknowledge that the decision to represent the information in this way was deliberate. A major goal of the report is to incentivize an organization to set a policy of `p=reject`, not necessarily to track one-to-one with the [interim deadlines](https://cyber.dhs.gov/guide/#checklist) that have been set by the directive. 

And yet, I think your point is fair: we're not really giving agencies credit for their efforts to hit those deadlines, and there's some obvious ways we can represent that back to you (domains without _any_ DMARC record, or that lack our rua=mailto:).

Thanks for sharing your feedback, @boberlas. Please feel free to comment further about the ways this report can be more helpful to you and your organization.

**Comment by h-m-f-t** [comment]
Closing, as the deadline mentioned has passed. <3 @boberlas
