### ISSUE TITLE
Clarify guidance around scope of order regarding which domains are covered

### ISSUE THREAD

**Issue by AntiFreeze** [cisagov/cyber.dhs.gov#31]
We have seen confusion around exactly which domains an agency needs to apply the measures from BOD 18-01 to, in order for the agency to be "in compliance."

Fixing this might be as simple as updating two spots in the Compliance Checklist:
- For 90 days, second bullet: "Configure all second-level domains **and non-mail-sending domains**..."
- Within 1 year: "for all second-level domains, **non-mail-sending-domains,** and mail-sending hosts."

@h-m-f-t thoughts?

**Comment by h-m-f-t** [comment]
Closing for now. :wave:@AntiFreeze
