### ISSUE TITLE
Idea: Coordination with CISA Chief Data Officer to implement data standards for this list (and systems that use it).

### ISSUE THREAD

**Issue by epinedactr** [cisagov/cyber.dhs.gov#314]
# 💡 Summary #

The CISA Chief Data Officer (CDO) is working on data standards, and I think some of them should apply here!

## Motivation and context ##

Implementing data standards helps facilitate common understanding, data sharing, and system interoperability across CISA and DHS.

## Implementation notes ##

Requesting contributors reach out to your data steward at CISA or the CDO Office to discuss further. There is a form to submit proposed changes to the data standards on CISA's intranet.

## Acceptance criteria ##

When all the values on this list correspond with the data standard and are implemented for systems that rely on this list. Ideally, automate the process for updating this list to correspond with the data standards.

**Comment by h-m-f-t** [comment]
This site is being retired in favor of cisa.gov/directives.
