### ISSUE TITLE
Add DKIM to domains that don't send email

### ISSUE THREAD

**Issue by cheyrou23** [cisagov/cyber.dhs.gov#60]
We're about to update our own guidance on this:
https://www.gov.uk/guidance/protect-domains-that-dont-send-email
to suggest people add a wildcard DKIM record to make it more likely email will get rejected.

"Create an empty DKIM record with:
type: TXT
host or name: *._domainkey
value: v=DKIM1; p=

As this is a wildcard record you cannot check it other than to look in the DNS host admin panel.
Revoke all existing DKIM selectors in both TXT and CNAME records.
This record will make email servers more likely to reject email from your domain."

**Comment by jimfenton** [comment]
This is not the way to do this. DKIM does not make any negative assertions, e.g., that a domain doesn't send email or that a given message is invalid. It only makes the assertion that the signing domain, usually the originating domain but not necessarily, signed it.

If you want to assert that the domain doesn't send email, use an SPF -all record, or look at DMARC. 

[for identification purposes, I'm one of the authors of RFC 4871]

**Comment by h-m-f-t** [comment]
@jimfenton said it better than I made time for, thank you. 🙏
