### ISSUE TITLE
Are vulnerabilities found in Government created apps in scope?

### ISSUE THREAD

**Issue by sei-vsarvepalli** [cisagov/cyber.dhs.gov#92]
The directory of Government apps can be found using the followin URL
https://www.usa.gov/mobile-apps

If vulnerabilities are found in these apps, can they also be reported through this process? 

Will it be possible to use the same .well-known/ security contacts for each Government sponsored or developed apps?

It seems useful to consider mobile and embrace these issues as well.

**Comment by adetaylor** [comment]
I was about to ask the same. The directive is built around internet-accessible web services, but it would be great if researchers felt they could also report vulnerabilities in other bits of Government software.

Apps would seem like the first obvious candidate. But it could potentially expand even beyond that - taking an extreme example, voting machines with physical flaws.
